### ISSUE TITLE
Is it possible to use cram as an input file? 

### ISSUE THREAD

**Issue by parkjooyoung99** [CuppenResearch/bamMetrics#25]
Dear developer,

I am currently using bamMetrics for analysis, and I've found it inconvenient to always convert cram files to bam files. Would there be a possibility for you to update the tool to accept cram files as input?

Thank you!

**Comment by rernst** [comment]
Hi [parkjooyoung99](https://github.com/parkjooyoung99),

Unfortunately we do not use this tool anymore and therefore don't maintain it. Feel free to create a fork to adjust the tool yourself. 

Best,
Robert
