### ISSUE TITLE
h_vmem reserved memory too small

### ISSUE THREAD

**Issue by hinri** [CuppenResearch/bamMetrics#5]
In: /hpc/local/CentOS7/cog_bioinf/bamMetrics/bamMetrics.pl

my $queue_mem = 8;
my $picard = "java -Xmx".$queue_mem."G
system "qsub -l h_rt=$args{queueTime},h_vmem=$args{queueMem}G

however, according to my experiences java takes 1.25 times more memory than it claims to use so:
h_vmem=($args{queueMem}*1.25)."G "

If you give it less then jobs exits with:
Error occurred during initialization of VM
Could not reserve enough space for 8388608KB object heap

**Comment by rernst** [comment]
Fixed this for java jobs.
