### ISSUE TITLE
h_vmem reserved memory stil too small

### ISSUE THREAD

**Issue by hinri** [CuppenResearch/bamMetrics#6]
In iterative tests it turns out that even a 1.25 multiplication factor is not sufficient.
According to my experiences a  multiplication factor doesn't describe the VM overhead very well.
A +4G fits better.

**Comment by rernst** [comment]
Fixed: https://github.com/CuppenResearch/bamMetrics/commit/f3a8fd109a47eca153b56a9e4d3137699498da76
